# Number of days of inactivity before an issue becomes stale
daysUntilStale: 5
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 8
# Issues with these labels will never be considered stale
exemptLabels:
  - "Estória"
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Este issue foi marcado automaticamente como caduco porque não teve
  atividade recentemente. Ele será fechado se não ocorrer mais atividades.
  Obrigado por sua contribuição.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
