# Configuration for weekly-digest - https://github.com/apps/weekly-digest
publishDay: tue
canPublishIssues: true
canPublishPullRequests: true
canPublishContributors: true
canPublishStargazers: False
canPublishCommits: true
